network:
  ethernets:
    enp0s25:
      addresses:
      - 192.168.0.100/24
      gateway4: 192.168.0.1
      nameservers:
        addresses:
        - 1.1.1.1
        - 8.8.8.8
        - 4.4.4.4
        search:
        - example.com
        - sales.example.com
        - dev.example.com
  renderer: networkd
  version: 2
